# -*- coding: utf-8 -*-
#|param_flanec

import os
from pydoc import doc
import pythoncom
from win32com.client import Dispatch, gencache

import LDefin2D
import MiscellaneousHelpers as MH

#  Подключим константы API Компас
kompas6_constants = gencache.EnsureModule("{75C9F5D0-B5B8-4526-8681-9903C567D2ED}", 0, 1, 0).constants
kompas6_constants_3d = gencache.EnsureModule("{2CAF168C-7961-4B90-9DA2-701419BEEFE3}", 0, 1, 0).constants

#  Подключим описание интерфейсов API5
kompas6_api5_module = gencache.EnsureModule("{0422828C-F174-495E-AC5D-D31014DBBE87}", 0, 1, 0)
kompas_object = kompas6_api5_module.KompasObject(Dispatch("Kompas.Application.5")._oleobj_.QueryInterface(kompas6_api5_module.KompasObject.CLSID, pythoncom.IID_IDispatch))
MH.iKompasObject  = kompas_object

#  Подключим описание интерфейсов API7
kompas_api7_module = gencache.EnsureModule("{69AC2981-37C0-4379-84FD-5DD2F3C0A520}", 0, 1, 0)
application = kompas_api7_module.IApplication(Dispatch("Kompas.Application.7")._oleobj_.QueryInterface(kompas_api7_module.IApplication.CLSID, pythoncom.IID_IDispatch))
MH.iApplication  = application


# Documents = application.Documents
# #  Получим активный документ
# kompas_document = application.ActiveDocument
# kompas_document_3d = kompas_api7_module.IKompasDocument3D(kompas_document)
# iDocument3D = kompas_object.ActiveDocument3D()

#  Создаем новый документ
for i in range(10):
    i = i + 2
    Documents = application.Documents
    kompas_document = Documents.AddWithDefaultSettings(kompas6_constants.ksDocumentPart, True)

    kompas_document_3d = kompas_api7_module.IKompasDocument3D(kompas_document)
    iDocument3D = kompas_object.ActiveDocument3D()

    #Нахождение пути
    path = path = os.path.dirname(os.path.abspath(__file__)) + "/"
    os.chdir(path)


    # Подключение переменных из экселя
    Excel = Dispatch('Excel.Application')
    book = Excel.Workbooks.open(r"F:\GIT\MACROS\Создание параметрических деталей\БТЛИ.711142 Фланец.xlsx").ActiveSheet
    listEx=Excel.ActiveSheet
    d = book.Cells(i,1).value
    D = book.Cells(i,2).value
    s = book.Cells(i,3).value
    do = book.Cells(i,4).value
    n = book.Cells(i,5).value
    mo = book.Cells(i,6).value
    oboz = listEx.Cells(i,7).value
    name = listEx.Cells(i,8).value
    file_name = str(oboz + name)

    iPart7 = kompas_document_3d.TopPart
    iPart = iDocument3D.GetPart(kompas6_constants_3d.pTop_Part)

    iSketch = iPart.NewEntity(kompas6_constants_3d.o3d_sketch)
    iDefinition = iSketch.GetDefinition()
    iPlane = iPart.GetDefaultEntity(kompas6_constants_3d.o3d_planeYOZ)
    iDefinition.SetPlane(iPlane)
    iSketch.Create()
    iDocument2D = iDefinition.BeginEdit()
    kompas_document_2d = kompas_api7_module.IKompasDocument2D(kompas_document)
    iDocument2D = kompas_object.ActiveDocument2D()

        # Создание эскиза
    obj = iDocument2D.ksCircle(0, 0, d/2, 1)
    obj = iDocument2D.ksCircle(0, 0, D/2, 1)
    iDefinition.EndEdit()

    # Выдавливание
    iPart7 = kompas_document_3d.TopPart
    iPart = iDocument3D.GetPart(kompas6_constants_3d.pTop_Part)

    obj = iPart.NewEntity(kompas6_constants_3d.o3d_bossExtrusion)
    iDefinition = obj.GetDefinition()
    iCollection = iPart.EntityCollection(kompas6_constants_3d.o3d_edge)
    iCollection.SelectByPoint(0, -d/2, 0)
    iEdge = iCollection.Last()
    iEdgeDefinition = iEdge.GetDefinition()
    iSketch = iEdgeDefinition.GetOwnerEntity()
    iDefinition.SetSketch(iSketch)
    iExtrusionParam = iDefinition.ExtrusionParam()
    iExtrusionParam.direction = kompas6_constants_3d.dtNormal
    iExtrusionParam.depthNormal = s
    iExtrusionParam.depthReverse = 0
    iExtrusionParam.draftOutwardNormal = False
    iExtrusionParam.draftOutwardReverse = False
    iExtrusionParam.draftValueNormal = 0
    iExtrusionParam.draftValueReverse = 0
    iExtrusionParam.typeNormal = kompas6_constants_3d.etBlind
    iExtrusionParam.typeReverse = kompas6_constants_3d.etBlind
    iThinParam = iDefinition.ThinParam()
    iThinParam.thin = False
    obj.name = "Элемент выдавливания:1"
    iColorParam = obj.ColorParam()
    iColorParam.ambient = 0.5
    iColorParam.color = 3960127
    iColorParam.diffuse = 0.6
    iColorParam.emission = 0.5
    iColorParam.shininess = 0.8
    iColorParam.specularity = 0.8
    iColorParam.transparency = 1
    obj.Create()

    # Вырезание отверстий
    iPart7 = kompas_document_3d.TopPart
    iPart = iDocument3D.GetPart(kompas6_constants_3d.pTop_Part)

    iSketch = iPart.NewEntity(kompas6_constants_3d.o3d_sketch)
    iDefinition = iSketch.GetDefinition()
    iPlane = iPart.GetDefaultEntity(kompas6_constants_3d.o3d_planeYOZ)
    iDefinition.SetPlane(iPlane)
    iSketch.Create()
    iDocument2D = iDefinition.BeginEdit()
    kompas_document_2d = kompas_api7_module.IKompasDocument2D(kompas_document)
    iDocument2D = kompas_object.ActiveDocument2D()

    obj = iDocument2D.ksCircle(-mo/2, 0, do/2, 1)
    iDefinition.EndEdit()
    iPart7 = kompas_document_3d.TopPart
    iPart = iDocument3D.GetPart(kompas6_constants_3d.pTop_Part)

    obj = iPart.NewEntity(kompas6_constants_3d.o3d_cutExtrusion)
    iDefinition = obj.GetDefinition()
    iCollection = iPart.EntityCollection(kompas6_constants_3d.o3d_edge)
    iCollection.SelectByPoint(0, 0, mo/2-do/2)
    iEdge = iCollection.Last()
    iEdgeDefinition = iEdge.GetDefinition()
    iSketch = iEdgeDefinition.GetOwnerEntity()
    iDefinition.SetSketch(iSketch)
    iDefinition.cut = True
    iExtrusionParam = iDefinition.ExtrusionParam()
    iExtrusionParam.direction = kompas6_constants_3d.dtNormal
    iExtrusionParam.depthNormal = -s
    iExtrusionParam.depthReverse = 0
    iExtrusionParam.draftOutwardNormal = False
    iExtrusionParam.draftOutwardReverse = False
    iExtrusionParam.draftValueNormal = 0
    iExtrusionParam.draftValueReverse = 0
    iExtrusionParam.typeNormal = kompas6_constants_3d.etBlind
    iExtrusionParam.typeReverse = kompas6_constants_3d.etBlind
    iThinParam = iDefinition.ThinParam()
    iThinParam.thin = False
    obj.name = "Элемент выдавливания:2"
    iColorParam = obj.ColorParam()
    iColorParam.ambient = 0.5
    iColorParam.color = 3960127
    iColorParam.diffuse = 0.6
    iColorParam.emission = 0.5
    iColorParam.shininess = 0.8
    iColorParam.specularity = 0.8
    iColorParam.transparency = 1
    obj.Create()

    # Массив из отверстий
    iPart7 = kompas_document_3d.TopPart
    iPart = iDocument3D.GetPart(kompas6_constants_3d.pTop_Part)

    obj = iPart.NewEntity(kompas6_constants_3d.o3d_circularCopy)
    iDefinition = obj.GetDefinition()
    iDefinition.count1 = 1
    iDefinition.count2 = n
    iDefinition.factor1 = False
    iDefinition.factor2 = True
    iDefinition.geomArray = False
    iDefinition.inverce = False
    iDefinition.step1 = 10
    iDefinition.step2 = 360
    iAxis = iPart.GetDefaultEntity(kompas6_constants_3d.o3d_axisOX)
    iDefinition.SetAxis(iAxis)
    iArray = iDefinition.GetOperationArray()
    iCollection = iPart.EntityCollection(kompas6_constants_3d.o3d_edge)
    iCollection.SelectByPoint(-s, -do/2, mo/2)
    iEdge = iCollection.Last()
    iEdgeDefinition = iEdge.GetDefinition()
    iOperation = iEdgeDefinition.GetOwnerEntity()
    iArray.Add(iOperation)
    obj.name = "Массив по концентрической сетке:1"
    iColorParam = obj.ColorParam()
    iColorParam.ambient = 0.5
    iColorParam.color = 3960127
    iColorParam.diffuse = 0.6
    iColorParam.emission = 0.5
    iColorParam.shininess = 0.8
    iColorParam.specularity = 0.8
    iColorParam.transparency = 1
    obj.Create()

    print(path)

    kompas_document.SaveAs(path + file_name + '.m3d')
    print(file_name)
    kompas_document.Close(False)
